// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Official support",
            "url": "https://kekasi.co.id/en/contact/",
            "email": "arditya@kekasi.co.id"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tools/json/format": {
            "post": {
                "description": "Format a raw JSON string into pretty JSON",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tools"
                ],
                "summary": "Format JSON data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request ID (alphanumeric, max 50 chars)",
                        "name": "request-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "JSON data to format",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FormatJsonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.FormatJsonResponseSwag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.SwaggRespError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.FormatJsonRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "{\"name\":\"kekasi\",\"age\":25}"
                }
            }
        },
        "model.FormatJsonResponse": {
            "type": "object",
            "properties": {
                "formatted": {
                    "type": "string",
                    "example": "{\n  \"name\": \"kekasi\",\n  \"age\": 25\n}"
                }
            }
        },
        "model.FormatJsonResponseSwag": {
            "type": "object",
            "properties": {
                "response_code": {
                    "type": "string",
                    "example": "200"
                },
                "response_data": {
                    "$ref": "#/definitions/model.FormatJsonResponse"
                },
                "response_desc": {
                    "type": "string",
                    "example": "success"
                },
                "response_id": {
                    "type": "string",
                    "example": "abc-123"
                },
                "response_refnum": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "model.SwaggRespError": {
            "type": "object",
            "properties": {
                "response_code": {
                    "type": "string",
                    "example": "400"
                },
                "response_data": {},
                "response_desc": {
                    "type": "string",
                    "example": "data is required"
                },
                "response_id": {
                    "type": "string",
                    "example": "abc-123"
                },
                "response_refnum": {
                    "type": "string",
                    "example": ""
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7070",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go API Tools by Arditya Kekasi",
	Description:      "A collection of API tools in Go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
